### ISSUE TITLE
TypeError: process_resource() takes exactly 4 arguments (5 given)

### ISSUE THREAD

**Issue by maks123** [werwolfby/monitorrent#105]
Hi.
maksim@cube:~/monitorent$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04 64bit
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

**Step to reproduce:**
1. pip install -r requirements.txt
    **completed without error**
2. python server.py
Server started on 0.0.0.0:6687
3. goto http://10.0.0.7:6687/
**Actual result:**
TypeError('process_resource() takes exactly 4 arguments (5 given)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1360, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 875, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2255, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2465, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 187, in __call__
    params)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 561, in _call_rsrc_mw
    process_resource(req, resp, resource, params)
TypeError: process_resource() takes exactly 4 arguments (5 given)
TypeError('process_resource() takes exactly 4 arguments (5 given)',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 1360, in communicate
    req.respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 875, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2255, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/wsgiserver/wsgiserver2.py", line 2465, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 187, in __call__
    params)
  File "/usr/local/lib/python2.7/dist-packages/falcon/api.py", line 561, in _call_rsrc_mw
    process_resource(req, resp, resource, params)
TypeError: process_resource() takes exactly 4 arguments (5 given)
^C
maksim@cube:~/monitorent$

**Comment by werwolfby** [comment]
Workaround in: https://github.com/werwolfby/monitorrent/issues/103
We will fix it next release: https://github.com/werwolfby/monitorrent/issues/104

**Comment by werwolfby** [comment]
Can I close issue?

**Comment by werwolfby** [comment]
Release [1.0.1](https://github.com/werwolfby/monitorrent/releases/tag/1.0.1) has fixed the issue

**Comment by maks123** [comment]
Thank you! With 1.1.0-rc all work.

**Comment by werwolfby** [comment]
@maks123 you can use 1.0.1 as latest stable instead
