### ISSUE TITLE
Exception while execute topic: unsupported operand type(s) for %: 'bytes' and 'tuple'

### ISSUE THREAD

**Issue by Clerik-owl** [werwolfby/monitorrent#176]
Про проверке раздач на рутрекере возникает ошибка.

```
INFO
Begin execute
INFO
Start checking for rutracker.org
INFO
Credentials/Settings are valid
INFO
Check for changes Однажды в Сказке / Once Upon a Time / Сезон: 5 / Серии: 1-23 из 23 (Ральф Хемекер, Рон Андервуд) [2015, США, Фэнтези, мелодрама, приключения, WEB-DL 720p] Dub (Невафильм) + Original + Subs (Rus, Eng)
FAILED
Exception while execute topic: unsupported operand type(s) for %: 'bytes' and 'tuple'
INFO
End checking for rutracker.org
INFO
End execute
```

Linux 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux.
 запущен из сорс кода "как есть".
debian jessie

**Comment by werwolfby** [comment]
> Python 3.4.2

**Comment by werwolfby** [comment]
Issue stacktrace:
```
FAILED
Exception while execute
Traceback (most recent call last):
File "/opt/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 575, in execute
TopicSettings.from_topic(topic))
File "/opt/monitorrent/monitorrent/engine.py", line 315, in add_torrent
return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
File "/opt/monitorrent/monitorrent/engine.py", line 83, in add_torrent
existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
File "/opt/monitorrent/monitorrent/utils/bittorrent.py", line 296, in info_hash
info_data = encode_dictionary(self.content['info'])
File "/opt/monitorrent/monitorrent/utils/bittorrent.py", line 176, in encode_dictionary
encoded += bencode(key)
File "/opt/monitorrent/monitorrent/utils/bittorrent.py", line 194, in bencode
return encode_functype(data)
File "/opt/monitorrent/monitorrent/utils/bittorrent.py", line 156, in encode_unicode
return encode_string(data.encode('utf8'))
File "/opt/monitorrent/monitorrent/utils/bittorrent.py", line 152, in encode_string
return b"%d:%s" % (len(data), data)
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

**Comment by werwolfby** [comment]
Behavior for python 3.4 and python 3.5 is differ:
```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> data = '123123'
>>> b"%d:%s" % (len(data), data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
>>> exit()

C:\Python35>python.exe
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> data = '123123'
>>> b"%d:%s" % (len(data), data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: %b requires bytes, or an object that implements __bytes__, not 'str'
```

**Comment by werwolfby** [comment]
Проблема явно была в питоне 3.4:

```
C:\Python34>python.exe
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> data = b'123123'
>>> b"%d:%s" % (len(data), data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
>>> exit()

C:\Python35>python.exe
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> data = b'123123'
>>> b"%d:%s" % (len(data), data)
b'6:123123'
>>> exit()
```

**Comment by werwolfby** [comment]
Изменение 267ee18f9d18e3607329eaea4ead707d57718af2 пофиксало проблему
