### ISSUE TITLE
Проблема с кодировкой при наличии русских букв в пути загрузки

### ISSUE THREAD

**Issue by abaistov** [werwolfby/monitorrent#178]
ОС Ubuntu 16.01
Возникает следующая ошибка:
```
FAILED
Exception while execute
Traceback (most recent call last):
  File "/opt/transmission/Moni/monitorrent/plugins/trackers/lostfilm.py", line 575, in execute
    TopicSettings.from_topic(topic))
  File "/opt/transmission/Moni/monitorrent/engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/opt/transmission/Moni/monitorrent/engine.py", line 86, in add_torrent
    elif self.clients_manager.add_torrent(torrent.raw_content, topic_settings):
  File "/opt/transmission/Moni/monitorrent/plugin_managers.py", line 217, in add_torrent
    return self.default_client.add_torrent(torrent, topic_settings)
  File "/opt/transmission/Moni/monitorrent/plugins/clients/transmission.py", line 109, in add_torrent
    client.add_torrent(base64.b64encode(torrent).decode('utf-8'), **torrent_settings_dict)
  File "/usr/local/lib/python2.7/dist-packages/transmissionrpc/client.py", line 414, in add_torrent
    (arg, val) = argument_value_convert('torrent-add', argument, value, self.rpc_version)
  File "/usr/local/lib/python2.7/dist-packages/transmissionrpc/utils.py", line 153, in argument_value_convert
    return (argument, TR_TYPE_MAP[info[0]](value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 27-32: ordinal not in range(128)

```

**Comment by werwolfby** [comment]
Ну это ожидаемо, чёрт побери!
Вылечим.

**Comment by abaistov** [comment]
на убунте проще использовать python 3.5 - в нем проблема отсутсвует.

**Comment by werwolfby** [comment]
Да я уже к какой-то такой ишью писал, что мол на 3-й питон надо перейти, там таких проблем не будет

**Comment by abaistov** [comment]
в таком случае, не проще ли отказаться от 2 версии, чтобы не тратить на это время? вообщем, лично для меня проблемка более не актуальна :)

**Comment by werwolfby** [comment]
Возможно :) Я уже об этом задумываюсь :)

**Comment by werwolfby** [comment]
Фиксается переездом на 3-й питон.
