### ISSUE TITLE
kinozal.tv error

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#179]
Ошибка не на всех раздачах, пример раздачи, на которой возникает при обновлении, первоначальное добавление прошло успешно - http://kinozal.tv/details.php?id=1479076

```
FAILED
Exception while execute topic
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 222, in execute
    torrent = Torrent(torrent_content)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\bittorrent.py", line 212, in __init__
    self.content = bdecode(content)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\bittorrent.py", line 143, in bdecode
    raise SyntaxError("syntax error: %s" % e)
SyntaxError: syntax error: 'generator' object is not an iterator
```

**Comment by Shooshka** [comment]
Ну и с 3ьего питона лог, пусть будет.

`
FAILED
Exception while execute topic
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\bittorrent.py", line 139, in bdecode
    data = decode_item(functools.partial(next, src), next(src))  # pylint:disable=E1101
  File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\bittorrent.py", line 97, in tokenize
    s = m.group(m.lastindex)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 222, in execute
    torrent = Torrent(torrent_content)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\bittorrent.py", line 212, in __init__
    self.content = bdecode(content)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\utils\bittorrent.py", line 143, in bdecode
    raise SyntaxError("syntax error: %s" % e)
  File "<string>", line None
SyntaxError: syntax error: 'NoneType' object has no attribute 'group'
`

**Comment by Shooshka** [comment]
upd: Связано с лимитом скачивания .torrent'a в сутки, а не с конкретной раздачей.
