### ISSUE TITLE
kinozal.tv error

### ISSUE THREAD

**Issue by Shooshka** [werwolfby/monitorrent#183]
```
FAILED
Exception while execute topic
Traceback (most recent call last):
File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers__init__.py", line 210, in execute
changed = self.check_changes(topic)
File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\kinozal.py", line 278, in check_changes
last_torrent_update = self.tracker.get_last_torrent_update(topic.url)
File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\kinozal.py", line 202, in get_last_torrent_update
last_update_text_element = content.find('b', text=self.last_update_text_re)
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by Shooshka** [comment]
2 вариант тоже с еррором:

FAILED
Exception while execute topic
Traceback (most recent call last):
File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers__init__.py", line 210, in execute
changed = self.check_changes(topic)
File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\kinozal.py", line 278, in check_changes
last_torrent_update = self.tracker.get_last_torrent_update(topic.url)
File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\kinozal.py", line 202, in get_last_torrent_update
last_update_text_element = content.find('div', text=self.last_update_text_re)
AttributeError: 'NoneType' object has no attribute 'find'
