### ISSUE TITLE
Exception while execute 'name'

### ISSUE THREAD

**Issue by skaa** [werwolfby/monitorrent#216]
Каждые два часа от бота в телеграмме получаю текст `Exception while execute 'name'`. В логах:
```
Exception while execute

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 245, in execute
    TopicSettings.from_topic(topic))
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 83, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugin_managers.py", line 204, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\clients\deluge.py", line 116, in find_torrent
    "name": torrent['name'],
KeyError: 'name'
```

**Comment by werwolfby** [comment]
Это значит что у вас ничего не качается сейчас :( 

В текущей девелоп версии уже исправлено. Вы где пользуетесь? Windows, Linux? Можно легко обновиться

**Comment by skaa** [comment]
Понятно. Перед постом смотрел открытые и закрытые ишью, не нашёл на эту тему. Windows с инсталлера 1.1.2. Галка Check for pre-release versions стоит, но я так понимаю, что такие версии не выпускаются пока.

**Comment by werwolfby** [comment]
Официально нет, но инсталер можно скачать

**Comment by werwolfby** [comment]
С appveyor, не могу на мобилке ссылку кинуть :(

**Comment by werwolfby** [comment]
Вот тут вот фиксалось: https://github.com/werwolfby/monitorrent/issues/200#issuecomment-281588437
