### ISSUE TITLE
deluge & lostfilm

### ISSUE THREAD

**Issue by lodgnewt** [werwolfby/monitorrent#219]
Может и не баг ))
НО при добавлении сериала скачивает торрент первой серии и подсвечивается красным
> 
FAILED
Exception while execute
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 784, in execute
    TopicSettings.from_topic(topic))
  File "/var/www/monitorrent/monitorrent/engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/var/www/monitorrent/monitorrent/engine.py", line 83, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 204, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/var/www/monitorrent/monitorrent/plugins/clients/deluge.py", line 116, in find_torrent
    "name": torrent['name'],
KeyError: 'name'

**Comment by werwolfby** [comment]
Это всё так же проблема, которая в девелопе пофиксана: #218

**Comment by lodgnewt** [comment]
умм, а докер можете обновить для х86?

**Comment by werwolfby** [comment]
Ну докера для новой версии ещё нет.
Ну я подумаю, может выпущу хот фикс сегодня тогда, а то вы уже 3-й с этим багом :)

**Comment by werwolfby** [comment]
И тогда да, обновлю докеры

**Comment by lodgnewt** [comment]
жду с нетерпением и огромное вам спасибо за мониторрент )

**Comment by werwolfby** [comment]
@lodgnewt долгова-то делал, но версия 1.1.3 готова, с фиксом для deluge (#200).
