### ISSUE TITLE
Проблема с lostfilm

### ISSUE THREAD

**Issue by lodgnewt** [werwolfby/monitorrent#222]
`FAILED
Exception while execute
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 784, in execute
    TopicSettings.from_topic(topic))
  File "/var/www/monitorrent/monitorrent/engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/var/www/monitorrent/monitorrent/engine.py", line 101, in add_torrent
    raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
Exception: Torrent American.Gods.S01E07.720p.WEB.rus.LostFilm.TV.mp4.torrent wasn't added`

**Comment by werwolfby** [comment]
Is it repeatable error?
Which version do you use? 
On what platform: x86 Windows, Linux, arm?
And what torrent client are you using?

**Comment by lodgnewt** [comment]
Оказалась моя ошибка. после смены адреса клиента нужно было вновь ввести пароль и сохранить.

**Comment by werwolfby** [comment]
Хух :)
