### ISSUE TITLE
Exception while execute

### ISSUE THREAD

**Issue by DatiQ** [werwolfby/monitorrent#258]
Не работает ни с одним из торрентов =(

`FAILED
Exception while execute
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 245, in execute
    TopicSettings.from_topic(topic))
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 101, in add_torrent
    raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
Exception: Torrent [kinozal.tv]id1581875.torrent wasn't added`

**Comment by werwolfby** [comment]
@DatiQ ну это похоже на то, что ниодин клиент не настроен.
Сам по себе monitorrent ничего не качает, он только передаёт торренты в торрент клиент: transmission, deluge, qbittorrent и другие.
Может так же качать в какую-то папку

**Comment by DatiQ** [comment]
@werwolfby можете перезалить инсталятор, а то ссылка не рабочая ;)

**Comment by werwolfby** [comment]
@DatiQ https://github.com/werwolfby/monitorrent/releases/tag/1.1.8 - тут рабочая

**Comment by DatiQ** [comment]
@werwolfby спасибо
