### ISSUE TITLE
AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)

### ISSUE THREAD

**Issue by ghost** [werwolfby/monitorrent#261]
Windows 10, Python 3.5.2
Manual Install
https://github.com/werwolfby/monitorrent/releases/download/1.1.6/monitorrent-1.1.6.zip 
    pip install -r requirements.txt
    python server.py

When I try to open
http://localhost:6687
I got the following:

f:\monitorent>python server.py
F:\Python35\lib\site-packages\alembic\util\messaging.py:69: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x000001D2048530B8>
  warnings.warn(msg)
Server started on 0.0.0.0:6687
AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 1183, in communicate
    req.parse_request()
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 663, in parse_request
    success = self.read_request_line()
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 862, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 862, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 1183, in communicate
    req.parse_request()
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 663, in parse_request
    success = self.read_request_line()
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 862, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 862, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 1183, in communicate
    req.parse_request()
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 663, in parse_request
    success = self.read_request_line()
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 862, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "F:\Python35\lib\site-packages\cheroot\server.py", line 862, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
Stopping engine
Stopping new_version_checker
Server stopped

**Comment by ibnlukum** [comment]
Наблюдаю подобную ошибку в Ubuntu 16.04. 
/opt/monitorrent# /usr/local/lib/python3.5/dist-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x7ff7a5f8c128>
  warnings.warn(msg)
Server started on 0.0.0.0:6687
AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1242, in communicate
    req.parse_request()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 712, in parse_request
    success = self.read_request_line()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 912, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 912, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
AttributeError("module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 1242, in communicate
    req.parse_request()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 712, in parse_request
    success = self.read_request_line()
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 912, in read_request_line
    for x in QUOTED_SLASH_REGEX.split(path)
  File "/usr/local/lib/python3.5/dist-packages/cheroot/server.py", line 912, in <listcomp>
    for x in QUOTED_SLASH_REGEX.split(path)
AttributeError: module 'six.moves.urllib_parse' has no attribute 'unquote_to_bytes'
