### ISSUE TITLE
Issues on macOS

### ISSUE THREAD

**Issue by ZChuckMoris** [werwolfby/monitorrent#264]
Юзаю python3.6.5 и python3.7. Получаю на обоих одну и ту же ошибку на macOS 10.12.6. Как пофиксить?

Exception while execute
Traceback (most recent call last):
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/plugins/trackers/__init__.py", line 245, in execute
    TopicSettings.from_topic(topic))
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/engine.py", line 83, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/plugin_managers.py", line 204, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/Users/moris/Desktop/Scripts/monitorrent/monitorrent/plugins/clients/utorrent.py", line 115, in find_torrent
    torrent = next(torrent for torrent in array if torrent[0] == torrent_hash)
StopIteration

**Comment by ZChuckMoris** [comment]
![image](https://user-images.githubusercontent.com/18584322/42740035-095a3b80-88aa-11e8-93c2-07745d9f6e37.png)
Скриншот прилагаю

**Comment by ZChuckMoris** [comment]
проблема решилась переустановкой версии 1.1.6 и накаткой изменённых файлов. Просьба к разработчику: обновите, пожалуйста, архивы и инсталлятор для винды до версии 1.1.7. Боюсь представить, сколько людей ещё наткнётся на те же ошибки, но не захочет ничего решать и заменять.
