### ISSUE TITLE
KeyError: 'Torrent not found in result'

### ISSUE THREAD

**Issue by RuPF** [werwolfby/monitorrent#266]
FAILED
Exception while execute
Traceback (most recent call last):
  File "/volume1/@appstore/monitorrent/monitorrent/plugins/trackers/__init__.py", line 245, in execute
    TopicSettings.from_topic(topic))
  File "/volume1/@appstore/monitorrent/monitorrent/engine.py", line 322, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/volume1/@appstore/monitorrent/monitorrent/engine.py", line 88, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/volume1/@appstore/monitorrent/monitorrent/plugin_managers.py", line 212, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/volume1/@appstore/monitorrent/monitorrent/plugins/clients/transmission.py", line 83, in find_torrent
    torrent = client.get_torrent(torrent_hash.lower(), ['id', 'hashString', 'addedDate', 'name'])
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/transmissionrpc/client.py", line 573, in get_torrent
    raise KeyError("Torrent not found in result")
KeyError: 'Torrent not found in result'

**Comment by n0rmed** [comment]
Та же ошибка. В докере на x86.
`Exception while execute
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 785, in execute
    TopicSettings.from_topic(topic))
  File "/var/www/monitorrent/monitorrent/engine.py", line 322, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/var/www/monitorrent/monitorrent/engine.py", line 88, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 212, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/var/www/monitorrent/monitorrent/plugins/clients/transmission.py", line 83, in find_torrent
    torrent = client.get_torrent(torrent_hash.lower(), ['id', 'hashString', 'addedDate', 'name'])
  File "/usr/local/lib/python3.6/site-packages/transmissionrpc/client.py", line 573, in get_torrent
    raise KeyError("Torrent not found in result")
KeyError: 'Torrent not found in result'`

**Comment by werwolfby** [comment]
Хммм.... кажется у меня тоже самое :)
А я и не заметил.
Завтра буду смотреть.

**Comment by SoiledBrush** [comment]
Есть продвижения? Только ознакомился с monitorrent, получаю ту же ошибку на версии 1.17.

**Comment by melnikdima90** [comment]
Аналогичная проблема

`FAILED
Exception while execute
Traceback (most recent call last):
  File "/opt/monitorrent/monitorrent/plugins/trackers/__init__.py", line 245, in execute
    TopicSettings.from_topic(topic))
  File "/opt/monitorrent/monitorrent/engine.py", line 322, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/opt/monitorrent/monitorrent/engine.py", line 88, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/opt/monitorrent/monitorrent/plugin_managers.py", line 212, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/opt/monitorrent/monitorrent/plugins/clients/transmission.py", line 83, in find_torrent
    torrent = client.get_torrent(torrent_hash.lower(), ['id', 'hashString', 'addedDate', 'name'])
  File "/usr/lib/python2.7/site-packages/transmissionrpc/client.py", line 573, in get_torrent
    raise KeyError("Torrent not found in result")
KeyError: 'Torrent not found in result'`

**Comment by lonsdaleite** [comment]
Та же проблема на роутере ZyXEL. Откат на 1.1.6 помог.

**Comment by werwolfby** [comment]
@RuPF, @lonsdaleite проверьте на 1.1.8, всё должно быть окей, и если ок то закройте ишью

**Comment by pltanton** [comment]
Работает, спасибо!
