### ISSUE TITLE
Не могу просканировать

### ISSUE THREAD

**Issue by gulbas** [werwolfby/monitorrent#268]
FAILED
Exception while execute topic
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 806, in _prepare_request
    episodes = [episode for season in show for episode in season
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 808, in <listcomp>
    (episode.season, episode.number) > latest_episode]
TypeError: unorderable types: int() > NoneType()

**Comment by werwolfby** [comment]
Странно, а что за сериал?

**Comment by werwolfby** [comment]
И на каком оборудовании запускаете?

**Comment by gulbas** [comment]
windows 10 Pro MonitorrentInstaller-1.1.7
Сериалы 
http://prntscr.com/ksbqfc

**Comment by werwolfby** [comment]
У меня локально похоже таже проблема, на днях будет фикс

**Comment by werwolfby** [comment]
@gulbas можете проверить на 1.1.8?

**Comment by gulbas** [comment]
@werwolfby где скачать?

**Comment by gulbas** [comment]
FAILED
Exception while execute
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 785, in execute
    TopicSettings.from_topic(topic))
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 101, in add_torrent
    raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
Exception: Torrent Fear.the.Walking.Dead.S04E02.rus.LostFilm.TV.avi.torrent wasn't added

**Comment by werwolfby** [comment]
@gulbas на главное теперь правильные ссылки :)
Ну а вообще все версии вот тут: https://github.com/werwolfby/monitorrent/releases
А последняя вот тут вот всегда: https://github.com/werwolfby/monitorrent/releases/latest (автоматический редирект на последнию версию): https://github.com/werwolfby/monitorrent/releases/tag/1.1.8
