### ISSUE TITLE
Некорректная работа с qBittorent после обновления

### ISSUE THREAD

**Issue by CooleRnax** [werwolfby/monitorrent#269]
Перестали качаться торренты, начал искать проблему, проблема с qBittorent.
```
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 785, in execute
    TopicSettings.from_topic(topic))
  File "/var/www/monitorrent/monitorrent/engine.py", line 322, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/var/www/monitorrent/monitorrent/engine.py", line 88, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 212, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/var/www/monitorrent/monitorrent/plugins/clients/qbittorrent.py", line 116, in find_torrent
    torrent = next(torrent for torrent in array if torrent['hash'] == torrent_hash)
StopIteration
```

**Comment by werwolfby** [comment]
Странно, завтра гляну

**Comment by werwolfby** [comment]
@CooleRnax 1.1.8 должен всё пофиксить, проверьте плиз и если всё ок, то закройте ишью

**Comment by CooleRnax** [comment]
заработало
