### ISSUE TITLE
Lostfilm.tv

### ISSUE THREAD

**Issue by Krab-11** [werwolfby/monitorrent#270]
Не могу добавить новые сериалы для загрузки с сайта lostfilm.tv. Проблема сохраняется на версии 1.1.6 и 1.1.7. На других не проверял. Monitorrent работает в докер контейнере на NAS с xpenology. Раньше проблем не было.
INFO
Begin execute

INFO
Start checking for lostfilm.tv

INFO
Credentials/Settings are valid

INFO
Check for changes Люцифер / Lucifer

INFO
Series Люцифер / Lucifer not changed

INFO
Check for changes Сверхъестественное / Supernatural

INFO
Series Сверхъестественное / Supernatural not changed

INFO
Check for changes Хороший доктор / The Good Doctor

FAILED
Exception while execute topic
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
    for season in self._parse_series(soup):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 524, in _parse_series
    serie_blocks = series_block.find_all('div', class_='serie-block')
AttributeError: 'NoneType' object has no attribute 'find_all'

INFO
End checking for lostfilm.tv

INFO
End execute

**Comment by werwolfby** [comment]
Да, уже в процессе, на днях выйдет фикс

**Comment by Leliil** [comment]
У меня так:
Traceback (most recent call last):
  File "/var/www/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 785, in execute
    TopicSettings.from_topic(topic))
  File "/var/www/monitorrent/monitorrent/engine.py", line 322, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "/var/www/monitorrent/monitorrent/engine.py", line 88, in add_torrent
    existing_torrent = self.clients_manager.find_torrent(torrent.info_hash)
  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 212, in find_torrent
    result = self.default_client.find_torrent(torrent_hash)
  File "/var/www/monitorrent/monitorrent/plugins/clients/transmission.py", line 83, in find_torrent
    torrent = client.get_torrent(torrent_hash.lower(), ['id', 'hashString', 'addedDate', 'name'])
  File "/usr/local/lib/python3.6/site-packages/transmissionrpc/client.py", line 573, in get_torrent
    raise KeyError("Torrent not found in result")
KeyError: 'Torrent not found in

**Comment by Krab-11** [comment]
Как успехи с фиксом? Когда ждать выхода?

**Comment by Leliil** [comment]
Я поставил 1.1.6 в докер, все работает

**Comment by hmvs** [comment]
В 1.1.7 по прежнему не работает. :(

**Comment by werwolfby** [comment]
@hmvs да с юбилейным числом похоже на правду, но вроде всё окей уже 1.1.8 всё пофиксил.
@Krab-11 можете проверить 1.1.8 и если всё ок, закрыть ишью

**Comment by hmvs** [comment]
@werwolfby спасибо. работает.

**Comment by RazielMalah** [comment]
Словил сегодня ту же проблему, версия свежая 1.10 конечно же
`FAILED
Exception while execute topic
Traceback (most recent call last):
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url
    for season in self._parse_series(soup):
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 524, in _parse_series
    serie_blocks = series_block.find_all('div', class_='serie-block')
AttributeError: 'NoneType' object has no attribute 'find_all'`

**Comment by RazielMalah** [comment]
Словил сегодня ту же проблему, версия свежая 1.1.10 конечно же
FAILED Exception while execute topic Traceback (most recent call last): File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute episodes = self._prepare_request(topic) File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request show = self.tracker.parse_url(topic.url, True) File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 515, in parse_url for season in self._parse_series(soup): File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 524, in _parse_series serie_blocks = series_block.find_all('div', class_='serie-block') AttributeError: 'NoneType' object has no attribute 'find_all'
