### ISSUE TITLE
Сервер стартует, но страница авторизации не отображается

### ISSUE THREAD

**Issue by zhivchegg** [werwolfby/monitorrent#276]
Страница авторизации
https://cdn1.savepice.ru/uploads/2018/11/9/6f508930b56cfc7037a581659911d107-full.jpg
Запуск:
[/opt/monitorent]$ python3.6 server.py
/usr/lib/python3.6/site-packages/alembic/util/messaging.py:69: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x7f02fb31f978>
  warnings.warn(msg)
Server started on 0.0.0.0:6687

Пробовал и под питоном 2.7 аналогичная ошибка

Делал по инструкции билд качал отсюда https://github.com/werwolfby/monitorrent/releases/download/1.1.8/monitorrent-1.1.8.zip

**Comment by ineggo** [comment]
Аналогичная проблема. Пока не решил

**Comment by jMurr** [comment]
Версия 1.1.10.
Такие ошибки:
```
root@sc:/opt/monitorrent# python3 server.py
/opt/monitorrent/monitorrent/upgrade_manager.py:35: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0xb51747d0>
  migration_context = MigrationContext.configure(session)
Server started on 0.0.0.0:6687
TypeError('process_response() takes 4 positional arguments but 5 were given')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1273, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/wsgi.py", line 143, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.7/dist-packages/falcon/api.py", line 286, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes 4 positional arguments but 5 were given
```

**Comment by werwolfby** [comment]
Теперь все должно быть хорошо
