### ISSUE TITLE
На лост филме все еще ошибка

### ISSUE THREAD

**Issue by butyc** [werwolfby/monitorrent#283]
Exception while execute
Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 785, in execute
    TopicSettings.from_topic(topic))
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 315, in add_torrent
    return self.engine.add_torrent(filename, torrent, old_hash, topic_settings)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 101, in add_torrent
    raise Exception(u'Torrent {0} wasn\'t added'.format(filename))
Exception: Torrent The.Orville.S02E02.720p.WEB.rus.LostFilm.TV.mp4.torrent wasn't added

добавляю сериал по ссылке: https://www.lostfilm.tv/series/The_Orville/seasons определяет все корректно..

**Comment by butyc** [comment]
версия 1.1.8, windows 10 pro...

**Comment by butyc** [comment]
понял, не добавляются сетевые папки.. только локальные..

**Comment by werwolfby** [comment]
@butyc можем закрывать?
