### ISSUE TITLE
Kinozal.tv error

### ISSUE THREAD

**Issue by DryginMax** [werwolfby/monitorrent#297]
Никак не могу настроить работу на зеркало https://kinozal-tv.appspot.com/
Я не програмист, но на какой то старой версии monitorret работало так:
```
class KinozalTracker(object):
    tracker_settings = None
    login_url = "https://kinozal-tv.appspot.com/takelogin.php"

    profile_page = "https://kinozal-tv.appspot.com/inbox.php"

    url_regex = re.compile(six.text_type(r'^https?://kinozal-tv.appspot\.com/details\.php\?.{9}&id=(\d+)$'))

    last_update_text_re = re.compile(u'^Торрент-файл обновлен\s+(.*)$', re.UNICODE | re.IGNORECASE)

    date_parser = KinozalDateParser()
```

Сейчас выдает ошибку
````
Exception while execute topic
Traceback (most recent call last):
  File "C:\monitorrent\monitorrent\plugins\trackers\__init__.py", line 212, in execute
    changed = self.check_changes(topic)

  File "C:\monitorrent\monitorrent\plugins\trackers\kinozal.py", line 278, in check_changes
    last_torrent_update = self.tracker.get_last_torrent_update(topic.url)

  File "C:\monitorrent\monitorrent\plugins\trackers\kinozal.py", line 202, in get_last_torrent_update
    last_update_text_element = content.find('b', text=self.last_update_text_re)

AttributeError: 'NoneType' object has no attribute 'find'
````
(Ошибка есть на версиях Monitorrent  с v.1.1.8 по v.1.1.10)
Да и основная проблема - не добавляются НОВЫЕ раздачи. т.е. не происходит идентификации торрента по добавляемой ссылке!
Что посоветуете?

**Comment by werwolfby** [comment]
Вопрос ещё актуальный? Если да, то переоткройте ишью.
