### ISSUE TITLE
Случайная недоступность некоторых сериалов на lostfilm

### ISSUE THREAD

**Issue by RazielMalah** [werwolfby/monitorrent#299]
Что-то часто по некоторым сериалам рандомно стала вылазить ошибка:
```
FAILED
Exception while execute topic
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 164, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x6b950510>, 'Connection to www.lostfilm.tv timed out. (connect timeout=10.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Max retries exceeded with url: /series/Billions/seasons (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x6b950510>, 'Connection to www.lostfilm.tv timed out. (connect timeout=10.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 736, in execute
    episodes = self._prepare_request(topic)
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 799, in _prepare_request
    show = self.tracker.parse_url(topic.url, True)
  File "/root/monitorrent/monitorrent/plugins/trackers/lostfilm.py", line 500, in parse_url
    **self.tracker_settings.get_requests_kwargs())
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Max retries exceeded with url: /series/Billions/seasons (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x6b950510>, 'Connection to www.lostfilm.tv timed out. (connect timeout=10.0)'))
```
Хотя сам ресурс стабильно доступен:
```
--- lostfilm.tv ping statistics ---
236 packets transmitted, 236 received, 0% packet loss, time 235330ms
rtt min/avg/max/mdev = 114.711/115.087/144.328/1.959 ms
```

**Comment by werwolfby** [comment]
Ну точно сайт пингуется быстро не значит, что открывается быстро, но по логам точно видно, что проблема в конекшене
