### ISSUE TITLE
Не могу добавить ни одну раздачу

### ISSUE THREAD

**Issue by RazielMalah** [werwolfby/monitorrent#317]
Одновременно в консоль сыпется это

```
root@DietPi:~/monitorrent# IntegrityError('(sqlite3.IntegrityError) UNIQUE constraint failed: topics.url')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: topics.url

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/wsgi.py", line 142, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.7/dist-packages/falcon/api.py", line 244, in __call__
    headers = resp._wsgi_headers(media_type)
  File "/root/monitorrent/monitorrent/rest/topics.py", line 24, in on_post
    added = self.tracker_manager.add_topic(url, settings)
  File "/root/monitorrent/monitorrent/plugin_managers.py", line 110, in add_topic
    if tracker.add_topic(url, params):
  File "/root/monitorrent/monitorrent/plugins/trackers/__init__.py", line 90, in add_topic
    db.add(topic)
  File "/root/monitorrent/monitorrent/db.py", line 25, in __exit__
    self.commit()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/persistence.py", line 1120, in _emit_insert_statements
    statement, params
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: topics.url
[SQL: INSERT INTO topics (display_name, url, last_update, type, download_dir) VALUES (?, ?, ?, ?, ?)]
[parameters: ('Рик и Морти / Rick and Morty / Сезон: 4 / Серии: 1 из 10 (Пит Мишелс, Брайан Ньютон, Джон Райс) [2019, США, Мультфильм, комедия, фантастика, WEB-DL 1080p] VO (Сыендук) + Original + Rus Sub', 'https://rutracker.org/forum/viewtopic.php?t=5804913', None, 'rutracker.org', '/mnt/HD/HD_a2/Public/Shared Videos/Shows/Rick and Morty')]
(Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by Akior** [comment]
Docker или прямой запуск через python ?

**Comment by werwolfby** [comment]
Закрываю за давностью
