### ISSUE TITLE
Ошибка при работе с nnmclub.to

### ISSUE THREAD

**Issue by Zeliboba4** [werwolfby/monitorrent#336]
Ошибка возникает при работе с nnmclub.to, но только на одной раздаче из тех что я мониторю, а именно на этой: http://nnmclub.to/forum/viewtopic.php?t=1366234
Остальные раздачи качает нормально.

Данные по ошибке:
Exception while execute topic
Traceback (most recent call last):
File "/root/monitorrent/plugins/trackers/__init__.py", line 218, in execute
    prepared_request = self._prepare_request(topic)
  File "/root/monitorrent/plugins/trackers/nnmclub.py", line 199, in _prepare_request
    return request.prepare()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 267, in prepare
    hooks=self.hooks,
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

**Comment by chemodun** [comment]
Попробуйте это
  https://github.com/chemodun/monitorrent/tree/377df8a2d330b2fd9d02c50570ddbfb9c93efdfd

**Comment by Zeliboba4** [comment]
**chemodun**, спасибо.
Обновил файл и все заработало.
