### ISSUE TITLE
Failed while checking for lostfilm.tv

### ISSUE THREAD

**Issue by MozzieMD** [werwolfby/monitorrent#337]
`Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Program Files (x86)\Monitorrent\env\lib\http\client.py", line 1322, in getresponse
    response.begin()
  File "C:\Program Files (x86)\Monitorrent\env\lib\http\client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files (x86)\Monitorrent\env\lib\http\client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Program Files (x86)\Monitorrent\env\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 131, in execute
    tracker.execute(topics, engine_tracker)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 735, in execute
    if not self._execute_login(engine):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 341, in _execute_login
    if not self.verify():
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 727, in verify
    return self.tracker.verify()
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 483, in verify
    r1 = scraper.get(my_settings_url, headers=self._headers, cookies=cookies,
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\cloudscraper\__init__.py", line 169, in request
    super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Read timed out. (read timeout=10.0)`
![image](https://user-images.githubusercontent.com/13788246/77808193-156a1a80-7093-11ea-9ec7-6be6c55cb50a.png)

**Comment by werwolfby** [comment]
Закрываю за давностью
