### ISSUE TITLE
[FALCON] [ERROR] GET / => Traceback (most recent call last):

### ISSUE THREAD

**Issue by RuPF** [werwolfby/monitorrent#351]
[**@** ~]$ python3 /volume1/@appstore/monitorrent/server.py
/volume1/@appstore/monitorrent/monitorrent/upgrade_manager.py:35: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x41fa3bc8>
  migration_context = MigrationContext.configure(session)
/volume1/@appstore/monitorrent/monitorrent/rest/__init__.py:156: DeprecatedWarning: Call to deprecated function __init__(...). API class may be removed in a future release, use falcon.App instead.
  return falcon.API(request_type=MonitorrentRequest, response_type=MonitorrentResponse, middleware=middleware)
Server started on 0.0.0.0:6687
2020-10-18 15:04:45 [FALCON] [ERROR] GET / => Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/falcon/app.py", line 321, in __call__
    responder(req, resp, **params)
  File "/volume1/@appstore/monitorrent/monitorrent/rest/static_file.py", line 56, in on_get
    resp.stream_len = os.path.getsize(file_path)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/falcon/response.py", line 220, in stream_len
    raise AttributeError(_STREAM_LEN_REMOVED_MSG)
AttributeError: The deprecated stream_len property was removed in Falcon 3.0. Please use Response.set_stream() or Response.content_length instead.

2020-10-18 15:04:45 [FALCON] [ERROR] GET / => Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/falcon/app.py", line 331, in __call__
    process_response(req, resp, resource, req_succeeded)
TypeError: process_response() takes 4 positional arguments but 5 were given

Chrome:
<error>
<title>500 Internal Server Error</title>
</error>

Ставил по стандарту как здесь
Python 3.x and pip
Download latest build: https://github.com/werwolfby/monitorrent/releases/download/1.1.12/monitorrent-1.1.12.zip Extract into monitorent folder
pip install -r requirements.txt
python server.py

**Comment by werwolfby** [comment]
Почти 3 года спустя :) пофикшену указанием четкой версии в requirements.txt
