### ISSUE TITLE
LostFilm.TV-run

### ISSUE THREAD

**Issue by k0st1kLOL** [werwolfby/monitorrent#352]
FAILED

Failed while checking for lostfilm.tv

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connection.py", line 337, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files (x86)\Monitorrent\env\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\connectionpool.py", line 637, in urlopen
    retries = retries.increment(method, url, error=e, _pool=self,
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Max retries exceeded with url: /my_settings (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)')))

Пару дней уже стал выдавать сообщение об ошибке. Использую в связке с прокси. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\engine.py", line 131, in execute
    tracker.execute(topics, engine_tracker)
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 735, in execute
    if not self._execute_login(engine):
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 341, in _execute_login
    if not self.verify():
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 727, in verify
    return self.tracker.verify()
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\lostfilm.py", line 483, in verify
    r1 = scraper.get(my_settings_url, headers=self._headers, cookies=cookies,
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\cloudscraper\__init__.py", line 169, in request
    super(CloudScraper, self).request(method, url, *args, **kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.lostfilm.tv', port=443): Max retries exceeded with url: /my_settings (Caused by

**Comment by werwolfby** [comment]
Не доверяет сертификату от лостфильма

**Comment by werwolfby** [comment]
Ваш прокси подменяет сертификат скорее всего, потому что у меня все прекрасно, и хром и мониторрент прекрасно работают с lostfilm.tv и никаких ошибок не выдают

**Comment by k0st1kLOL** [comment]
Странно, прописываю прокси в браузер, сайт открывается без проблем(прокся своя и там нет подмены сертов). rutracker работает без проблем. есть возможность прописать sock прокси?

**Comment by werwolfby** [comment]
Да есть в настройках есть раздел с прокси

**Comment by werwolfby** [comment]
В General если быть точнее

**Comment by k0st1kLOL** [comment]
так там типа 
https://user:PW@IP:3128 
пробывал прописать сокс прокси в виде 
https://user:PW@IP:1080

**Comment by werwolfby** [comment]
А что значит не работает? Не подхватывает прокси и мониторрент ничего не скачивает? Или падает с ССЛ ошибкой?
Если с ней то может и ССЛ прокси не доверяет

**Comment by k0st1kLOL** [comment]
2 строки для http и https, прописываю настройки для того и того, рутрекер и рутор работает, лост выкиывает журнал(тот что выше), кстати на прошлой неделе еще работало. на прокси не трогал ничего, мониторрент так же актуальный, когда обновлял уже и не вспомню

**Comment by werwolfby** [comment]
Ну и я обновлял мониторрент последний раз в Марте :), так что с его стороны точно ничего не менялось.

Ну я не могу сто процентов гарантировать, но я таки склоняюсь к версии что прокси подменяет сертификат, других причин пока не вижу :(. Странно что браузер под тем же прокси ведёт себя нормально.

В любом случае можно отключить проверку сертификата, что так себе решение, но оно возможно.

**Comment by k0st1kLOL** [comment]
прописал прокси в браузер, начал шарится по сайтам(вк/ютуб/рутор/рутрекер), все работает, лост в том числе. скорее всего оператор стал пытаться блокировать.

**Comment by k0st1kLOL** [comment]
можно отключить проверку только для лоста?

**Comment by werwolfby** [comment]
Ну без именений кода вообще никак ничего не сделать, но в целом можно

**Comment by k0st1kLOL** [comment]
Оператор обновил способы блокировок 
прошу прощения. Спасибо за программу)

**Comment by werwolfby** [comment]
https://github.com/werwolfby/monitorrent/blob/feature/ingore-lost-film-ssl/monitorrent/plugins/trackers/lostfilm.py
Вот копируете этот файл в:
C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\
С заменой и должнобыть

**Comment by werwolfby** [comment]
> Оператор обновил способы блокировок
> прошу прощения. Спасибо за программу)

Да ладно! Ну хорошо хоть не тестил фикс :)

**Comment by k0st1kLOL** [comment]
но добавить сокс и днс запросы через него всетаки стоило бы)))

**Comment by werwolfby** [comment]
Так сокс и днс через сокс и так работают :) добавлять нечего.
