### ISSUE TITLE
Не работает rutracker.org. Не добавляются новые ссылки на торрент файлы

### ISSUE THREAD

**Issue by urtaevS** [werwolfby/monitorrent#360]
raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/viewtopic.php?t=6132554 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/cheroot/server.py", line 1252, in communicate

    req.respond()

  File "/usr/local/lib/python3.8/site-packages/cheroot/server.py", line 1056, in respond

    self.server.gateway(self).respond()

  File "/usr/local/lib/python3.8/site-packages/cheroot/wsgi.py", line 142, in respond

    response = self.req.server.wsgi_app(self.env, self.start_response)

  File "/usr/local/lib/python3.8/site-packages/falcon/api.py", line 244, in __call__

    responder(req, resp, **params)

  File "/var/www/monitorrent/monitorrent/rest/topics.py", line 41, in on_get

    title = self.tracker_manager.prepare_add_topic(url)

  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 107, in prepare_add_topic

    parsed_url = tracker.prepare_add_topic(url)

  File "/var/www/monitorrent/monitorrent/plugins/trackers/__init__.py", line 71, in prepare_add_topic

    parsed_url = self.parse_url(url)

  File "/var/www/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 184, in parse_url

    return self.tracker.parse_url(url)

  File "/var/www/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 66, in parse_url

    r = requests.get(url, allow_redirects=False, **self.tracker_settings.get_requests_kwargs())

  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get

    return request('get', url, params=params, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request

    return session.request(method=method, url=url, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send

    raise SSLError(e, request=request)

requests.exceptions.SSLError: HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/viewtopic.php?t=6132554 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

/usr/local/lib/python3.8/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x7fb956233640>

  warnings.warn(msg)

socket.error MaxRetryError("HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/viewtopic.php?t=6132554 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))")

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 597, in urlopen

    httplib_response = self._make_request(conn, method, url,

  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 343, in _make_request

    self._validate_conn(conn)

  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn

    conn.connect()

  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 337, in connect

    self.sock = ssl_wrap_socket(

  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket

    return context.wrap_socket(sock, server_hostname=server_hostname)

  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket

    return self.sslsocket_class._create(

  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create

    self.do_handshake()

  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 637, in urlopen

    retries = retries.increment(method, url, error=e, _pool=self,

  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 399, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/viewtopic.php?t=6132554 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/cheroot/server.py", line 1252, in communicate

    req.respond()

  File "/usr/local/lib/python3.8/site-packages/cheroot/server.py", line 1056, in respond

    self.server.gateway(self).respond()

  File "/usr/local/lib/python3.8/site-packages/cheroot/wsgi.py", line 142, in respond

    response = self.req.server.wsgi_app(self.env, self.start_response)

  File "/usr/local/lib/python3.8/site-packages/falcon/api.py", line 244, in __call__

    responder(req, resp, **params)

  File "/var/www/monitorrent/monitorrent/rest/topics.py", line 41, in on_get

    title = self.tracker_manager.prepare_add_topic(url)

  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 107, in prepare_add_topic

    parsed_url = tracker.prepare_add_topic(url)

  File "/var/www/monitorrent/monitorrent/plugins/trackers/__init__.py", line 71, in prepare_add_topic

    parsed_url = self.parse_url(url)

  File "/var/www/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 184, in parse_url

    return self.tracker.parse_url(url)

  File "/var/www/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 66, in parse_url

    r = requests.get(url, allow_redirects=False, **self.tracker_settings.get_requests_kwargs())

  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get

    return request('get', url, params=params, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request

    return session.request(method=method, url=url, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request

    resp = self.send(prep, **send_kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send

    r = adapter.send(request, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send

    raise SSLError(e, request=request)

**Comment by Egorkat** [comment]
сайт теперь за CloudFlare...

**Comment by werwolfby** [comment]
Я там для лоста делаю фикс, для остальных тоже попытаюсь добавить.
