### ISSUE TITLE
Не работает прокси одновременно с обходом cloudflare

### ISSUE THREAD

**Issue by liquidblasted** [werwolfby/monitorrent#363]
С версией 1.2.0 не работает прокси, т.к. не добавлена его поддержка в rutracker и lostfilm черeз playwright.
"если кратко, то единственный рабочий способ обойти cloudflare защиту это использовать настоящий браузер. А потом уже из него я достаю куки чтобы выполнять остальные запросы. И вот прокси в браузер я не ставлю." (c)[werwolfby](https://github.com/werwolfby)

FAILED

Failed while checking for rutracker.org

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
self._prepare_proxy(conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 994, in _prepare_proxy
conn.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 364, in connect
self.sock = conn = self._connect_tls_proxy(hostname, conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 499, in connect_tls_proxy
socket = ssl_wrap_socket(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl.py", line 449, in ssl_wrap_socket
ssl_sock = ssl_wrap_socket_impl(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/privmsg.php?folder=inbox (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)'))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/www/monitorrent/monitorrent/engine.py", line 124, in execute
tracker.execute(topics, engine_tracker)
File "/var/www/monitorrent/monitorrent/plugins/trackers/init.py", line 337, in execute
if not self._execute_login(engine):
File "/var/www/monitorrent/monitorrent/plugins/trackers/init.py", line 342, in _execute_login
if not self.verify():
File "/var/www/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 230, in verify
return self.tracker.verify()
File "/var/www/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 143, in verify
profile_page_result = requests.get(self.profile_page, cookies=cookies,
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 513, in send
raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/privmsg.ph

**Comment by werwolfby** [comment]
Я уже кстати в отдельной ветке пофиксил, так что 1.2.1. Но с вин инсталятором все ещё проблемы, так что релиза нет :(

**Comment by werwolfby** [comment]
@liquidblasted проверьте плиз работу 1.2.4, должно работать и с прокси.

**Comment by werwolfby** [comment]
Блин, нет, [ветка отдельно висит](https://github.com/werwolfby/monitorrent/tree/feature/playwright-proxy) еще, постараюсь вспомнить почему не включил в билд.
