### ISSUE TITLE
Не доступны трекеры

### ISSUE THREAD

**Issue by urtaevS** [werwolfby/monitorrent#372]
Ни как не хочет проверять трекеры.
На серваке настроен wireguard. Но на другом серваке с этими настройками работал
>     responder(req, resp, **params)
  File "/var/www/monitorrent/monitorrent/rest/topics.py", line 41, in on_get
    title = self.tracker_manager.prepare_add_topic(url)
  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 104, in prepare_add_topic
    parsed_url = tracker.prepare_add_topic(url)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/__init__.py", line 78, in prepare_add_topic
    parsed_url = self.parse_url(url)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/nnmclub.py", line 194, in parse_url
    return self.tracker.parse_url(url)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/nnmclub.py", line 75, in parse_url
    r = requests.get(url, allow_redirects=False, **self.tracker_settings.get_requests_kwargs())
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nnmclub.to', port=443): Max retries exceeded with url: /forum/viewtopic.php?t=1509321 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa0588b54f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
socket.error MaxRetryError("HTTPConnectionPool(host='rutor.info', port=80): Max retries exceeded with url: /torrent/879971/dyshite-svobodno-2021-web-dlrip-ot-files-x (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa02655feb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa02655feb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='rutor.info', port=80): Max retries exceeded with url: /torrent/879971/dyshite-svobodno-2021-web-dlrip-ot-files-x (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa02655feb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/usr/local/lib/python3.9/site-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.9/site-packages/cheroot/wsgi.py", line 142, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.9/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/var/www/monitorrent/monitorrent/rest/topics.py", line 41, in on_get
    title = self.tracker_manager.prepare_add_topic(url)
  File "/var/www/monitorrent/monitorrent/plugin_managers.py", line 104, in prepare_add_topic
    parsed_url = tracker.prepare_add_topic(url)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/__init__.py", line 78, in prepare_add_topic
    parsed_url = self.parse_url(url)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/rutor.py", line 174, in parse_url
    return self.tracker.parse_url(url)
  File "/var/www/monitorrent/monitorrent/plugins/trackers/rutor.py", line 120, in parse_url
    r = requests.get(url, **self.tracker_settings.get_requests_kwargs())
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='rutor.info', port=80): Max retries exceeded with url: /torrent/879971/dyshite-svobodno-2021-web-dlrip-ot-files-x (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa02655feb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by urtaevS** [comment]
А такое появилось после переустановки:

/usr/local/lib/python3.9/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x7f56da2b1d90>
  warnings.warn(msg)
/usr/local/lib/python3.9/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x7fadc64edeb0>
  warnings.warn(msg)

**Comment by iteterin** [comment]
Аналогично: 

`Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/cheroot/server.py", line 1252, in communicate
    req.respond()
  File "/root/.local/lib/python3.8/site-packages/cheroot/server.py", line 1056, in respond
    self.server.gateway(self).respond()
  File "/root/.local/lib/python3.8/site-packages/cheroot/wsgi.py", line 142, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/root/.local/lib/python3.8/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/home/sa/monitorrent/monitorrent/rest/topics.py", line 41, in on_get
    title = self.tracker_manager.prepare_add_topic(url)
  File "/home/sa/monitorrent/monitorrent/plugin_managers.py", line 104, in prepare_add_topic
    parsed_url = tracker.prepare_add_topic(url)
  File "/home/sa/monitorrent/monitorrent/plugins/trackers/__init__.py", line 78, in prepare_add_topic
    parsed_url = self.parse_url(url)
  File "/home/sa/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 236, in parse_url
    return self.tracker.parse_url(url)
  File "/home/sa/monitorrent/monitorrent/plugins/trackers/rutracker.py", line 97, in parse_url
    r = requests.get(url, allow_redirects=False, **self.tracker_settings.get_requests_kwargs())
  File "/root/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='rutracker.org', port=443): Max retries exceeded with url: /forum/viewtopic.php?t=6298335 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1091: The handshake operation timed out')))`

**Comment by iteterin** [comment]
Леплю через прокси, сама инфа о торренте скачивается, но не может аутентифицироваться на рутрекере. тоже самое с лостфильмом.
