### ISSUE TITLE
1.2.3 Windows - Not start

### ISSUE THREAD

**Issue by iteterin** [werwolfby/monitorrent#383]
Версия:
https://github.com/werwolfby/monitorrent/releases/tag/1.2.3
ОС: Windows Server 2022 
Чистая установка (свежая ВМ, ОС разлита только-что, ОС с сайта МС без каких-либо вмешательств и настроек, все по умолчанию из коробки)

Traceback (most recent call last):
  File "C:\Program Files (x86)\Monitorrent\server.py", line 13, in <module>
    from monitorrent.plugin_managers import load_plugins, get_plugins, TrackersManager, DbClientsManager, NotifierManager
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugin_managers.py", line 6, in <module>
    from monitorrent.plugins.trackers import TrackerPluginBase, WithCredentialsMixin
  File "C:\Program Files (x86)\Monitorrent\monitorrent\plugins\trackers\__init__.py", line 19, in <module>
    from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\playwright\async_api\__init__.py", line 25, in <module>
    import playwright.async_api._generated
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\playwright\async_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\playwright\_impl\_connection.py", line 23, in <module>
    from greenlet import greenlet
  File "C:\Program Files (x86)\Monitorrent\env\lib\site-packages\greenlet\__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: DLL load failed while importing _greenlet: Не найден указанный модуль.
Для продолжения нажмите любую клавишу . . .

При старте под виндами - не находит модуль. Стартую от Администратора с явными правами Администратора

**Comment by werwolfby** [comment]
Сорри, пропустил.

Я посмотрю подробнее

**Comment by werwolfby** [comment]
Хмм... подтверждаю, в [Windows Sandbox](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview) воспроизвел туже ошибку.

Это тоже абсолютно чистая винда.

**Comment by werwolfby** [comment]
@iteterin попробуйте установить [Microsoft Visual C++ Redistributable](https://aka.ms/vs/17/release/vc_redist.x86.exe).

Должно помочь, я попробую их включить в инсталлерю

**Comment by iteterin** [comment]
Да, помогло, спасибо! Что то в эту сторону покапать не додумался.. :))
