### ISSUE TITLE
Контейнер с Monitorrent v.1.4.0 падает через несколько часов после старта

### ISSUE THREAD

**Issue by zalessky** [werwolfby/monitorrent#397]
Пришлось таки купить сервер, чтобы переехать с .1.1.12 на свежую 1.4.0 версию. 
Оказалось, что старая версия работает стабильнее. Аптайм месяцами. А вот с последней не все гладко. Каждый вечер обнаруживаю, что контейнер выключен. И это при том, что AUTOSTART для контейнера включен. 
И всякий раз в логах такая портянка: 

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 1299, in run
    self.function(*self.args, **self.kwargs)
  File "/var/www/monitorrent/monitorrent/new_version_checker.py", line 58, in execute_timer
    self.execute()
  File "/var/www/monitorrent/monitorrent/new_version_checker.py", line 66, in execute
    latest_release = self.get_latest_release()
  File "/var/www/monitorrent/monitorrent/new_version_checker.py", line 80, in get_latest_release
    response = requests.get(self.releases_url)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/werwolfby/monitorrent/releases (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
/usr/local/lib/python3.9/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x14a7bbacde20>
  warnings.warn(msg)
/usr/local/lib/python3.9/site-packages/alembic/util/messaging.py:73: UserWarning: 'connection' argument to configure() is expected to be a sqlalchemy.engine.Connection instance, got <sqlalchemy.orm.session.ContextSession object at 0x14aa03b4edc0>
  warnings.warn(msg)
```

**Comment by BAPK** [comment]
У меня подобные логи выводит когда сайт недоступен. К примеру если кинозал заблочил частые запросы или сайт заблокирован РКН

**Comment by eProtest1** [comment]
> н

![image](https://github.com/werwolfby/monitorrent/assets/163421560/c75217cc-ef68-4949-ad19-77603c3fc7d4)
видимо в этом проблема, может как-то подсунуть ему куки свои?)
