### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by wolfam0108** [werwolfby/monitorrent#404]
When running on Ubuntu 22.04 python server.py

`Traceback (most recent call last):
  File "/root/monitorrent/server.py", line 19, in <module>
    from monitorrent.rest.challenge_logs import ChallengeLogs
  File "/root/monitorrent/monitorrent/rest/__init__.py", line 6, in <module>
    import falcon
  File "/usr/local/lib/python3.10/dist-packages/falcon/__init__.py", line 30, in <module>
    from falcon.api import API  # NOQA
  File "/usr/local/lib/python3.10/dist-packages/falcon/api.py", line 21, in <module>
    from falcon import api_helpers as helpers, DEFAULT_MEDIA_TYPE, routing
  File "/usr/local/lib/python3.10/dist-packages/falcon/api_helpers.py", line 21, in <module>
    from falcon import util
  File "/usr/local/lib/python3.10/dist-packages/falcon/util/__init__.py", line 29, in <module>
    from falcon.util import structures
  File "/usr/local/lib/python3.10/dist-packages/falcon/util/structures.py", line 35, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):  # pragma: no cover
AttributeError: module 'collections' has no attribute 'MutableMapping'`

**Comment by LynxAS** [comment]
Ubuntu 22.04.4 LTS
'MutableMapping' moved to another package in Python 3.10
I faced the same problem. Solved it by installing Python 3.9 (via deadsnakes repo) and created venv for monitorrent using Python 3.9. Looks like works fine.
